export const AuthTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    TOKEN: "TOKEN",
    USER_PROFILE: "USER_PROFILE",
    USER: "USER",
    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT: "PRODUCT",
    REVIEW_LIST: "REVIEW_LIST",
    REVIEW: "REVIEW",
    REVIEW_HISTORY: "REVIEW_HISTORY",

    UPLOAD_REVIEW: "UPLOAD_REVIEW",
    INTEREST: "INTEREST",
    LIKE: "LIKE",
    LIKED_REVIEWS: "LIKED_REVIEWS",
    SEARCH: "SEARCH",
    EVENT: "EVENT",
    INSTAGRAM: "INSTAGRAM"
};