export const AuthTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    TOKEN: "TOKEN",
    USER_PROFILE: "USER_PROFILE",
    USER: "USER",
    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT: "PRODUCT",
    INTEREST: "INTEREST",
    LIKE: "LIKE",
    REVIEW_LIST: "REVIEW_LIST",
    LIKED_REVIEW: "LIKED_REVIEW",
    UPLOAD_REVIEW: "UPLOAD_REVIEW",
    SEARCH: "SEARCH",
    EVENT: "EVENT",
    INSTAGRAM: "INSTAGRAM"
};